name: EconomyAPI
version: '${project.version}'
main: org.maxrio22.economyapi.infrastructure.plugin.Main
api-version: '1.21'

commands:
  #  CURRENCY COMMANDS
  getcurrency:
    description: Obtiene informaci贸n sobre una divisa.
    usage: /getcurrency <id>
    permission: economyapi.getcurrency
  getcurrencies:
    description: Obtiene informaci贸n de todas las divisas.
    usage: /getcurrencies
    permission: economyapi.getcurrencies
  createcurrency:
    description: Crea una nueva divisa.
    usage: /createcurrency <name> <symbol> <exchange_rate> <inflation_rate>
    permission: economyapi.createcurrency
  updatecurrency:
    description: Actualiza una divisa existente.
    usage: /updatecurrency <id> <name> <symbol> <exchange_rate> <inflation_rate>
    permission: economyapi.updatecurrency
  deletecurrency:
    description: Elimina una divisa.
    usage: /deletecurrency <id>
    permission: economyapi.deletecurrency

  #  BANK COMMANDS
  getbank:
    description: Obtiene informaci贸n sobre un banco.
    usage: /getbank <id>
    permission: economyapi.getbank
  getbanks:
    description: Obtiene informaci贸n de todos los bancos.
    usage: /getbanks
    permission: economyapi.getbanks
  createbank:
    description: Crea un nuevo banco.
    usage: /createbank <name> <currency_id> <reserve_ratio> <interest_rate> <loan_interest_rate> <transaction_fee>
    permission: economyapi.createbank
  updatebank:
    description: Actualiza un banco existente.
    usage: /updatebank <id> <name> <currency_id> <reserve_ratio> <interest_rate> <loan_interest_rate> <transaction_fee> <status>
    permission: economyapi.updatebank
  deletebank:
    description: Elimina un banco.
    usage: /deletebank <id>
    permission: economyapi.deletebank

  #  ACCOUNT COMMANDS
  getaccount:
    description: Obtiene informaci贸n sobre una cuenta.
    usage: /getaccount <id>
    permission: economyapi.getaccount
  getaccountbyiban:
    description: Obtiene una cuenta a partir de su IBAN.
    usage: /getaccountbyiban <iban>
    permission: economyapi.getaccountbyiban
  getaccounts:
    description: Obtiene informaci贸n de todas las cuentas.
    usage: /getaccounts
    permission: economyapi.getaccounts
  createaccount:
    description: Crea una nueva cuenta bancaria.
    usage: /createaccount <owner_type> <owner_id> <bank_id> <balance> <type>
    permission: economyapi.createaccount
  updateaccount:
    description: Actualiza una cuenta existente.
    usage: /updateaccount <id> <balance> <bloqueado:true/false>
    permission: economyapi.updateaccount
  deleteaccount:
    description: Elimina una cuenta bancaria.
    usage: /deleteaccount <id>
    permission: economyapi.deleteaccount
